### ISSUE TITLE
Pre W10 support?

### ISSUE THREAD

**Issue by PetrMahdalicek** [Microsoft/WPFDXInterop#12]
Is this library supposed to work on Windows 8 or Windows 7?

**Comment by harikm86** [comment]
Yes, it should. Are you running into any issues?

**Comment by rrelyea** [comment]
We've focused on making Microsoft.Wpf.Interop.Directx.dll build with either the DirectX SDK (June 2010) or the Windows 10 SDK. Should run fine on those dev machines.
For runtime machines, the dll distributed in the NuGet package may have some dependencies that we need to describe. Please let us know details of any exceptions that you are seeing, that may point to the missing binaries. (We'll go test again as well.)

**Comment by PetrMahdalicek** [comment]
It was my fault. I used wpf interop dll that I compiled. When I replaced it with dll from your nuget package, all is fine.

Sorry for the false alarm...

**Comment by rrelyea** [comment]
Great. Closing then.
