### ISSUE TITLE
I can not add D3DVisualization.dll to references.

### ISSUE THREAD

**Issue by Mitra-M** [Microsoft/WPFDXInterop#24]
I built D3DVisualization.dll (D3DVisualization_winsdk) without any error (debug and release , 86 and 64bit ),  But I can not add it to references.

I got this error :

D3DVisualization.dll could not be added. Please make sure that the file is accessible , and it is a valid assembly or COM component.

**Comment by nikobarli** [comment]
D3DVisualization is a C++ (native) DLL. You cannot add it as reference to your C# project.

You probably want to see this: http://stackoverflow.com/a/33436369

**Comment by Mitra-M** [comment]
Thank you . (My question was stupid)
