### ISSUE TITLE
What's the differences between sharing Texture2D with original D3Dimage and the D3D11Image from this project?

### ISSUE THREAD

**Issue by holance** [Microsoft/WPFDXInterop#30]
What's the differences between using [DX11ImageSource](https://github.com/helix-toolkit/helix-toolkit/blob/develop/Source/HelixToolkit.Wpf.SharpDX/Controls/DX11ImageSource.cs) to shared texture2D with original D3Dimage and the D3D11Image implementation from this project? 

Is there any performance gain from using the D3D11Image or they are basically the same? Thanks.

**Comment by weltkante** [comment]
D3D11Image uses the normal D3DImage for its implementation (the D3DImage is actually the base class for D3D11Image), so it just saves you from writing the Direct3D9 interop yourself.
